module.exports = [
  { method: 'GET', path: '/dashboard', name: 'dashboard', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerDashboardController.index' },

  { method: 'GET', path: '/notifications', name: 'notifications.index', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerNotificationController.index' },
  { method: 'POST', path: '/notifications', name: 'notifications.store', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerNotificationController.store' },
  { method: 'POST', path: '/notifications/read-all', name: 'notifications.readAll', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerNotificationController.mark_all_read' },
  { method: 'GET', path: '/notifications/:id', name: 'notifications.show', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerNotificationController.show' },
  { method: 'PUT', path: '/notifications/:id', name: 'notifications.update', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerNotificationController.update' },
  { method: 'PATCH', path: '/notifications/:id', name: 'notifications.patch', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerNotificationController.update' },
  { method: 'DELETE', path: '/notifications/:id', name: 'notifications.destroy', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerNotificationController.destroy' },
  { method: 'POST', path: '/notifications/:id/read', name: 'notifications.read', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerNotificationController.mark_read' },

  { method: 'POST', path: '/profile', name: 'profile.store', middleware: ['auth', 'volunteer'], handler: 'volunteer/VolunteerProfileController.store' },
  { method: 'GET', path: '/profile', name: 'profile.show', middleware: ['auth', 'volunteer'], handler: 'volunteer/VolunteerProfileController.show' },
  { method: 'PUT', path: '/profile', name: 'profile.update', middleware: ['auth', 'volunteer'], handler: 'volunteer/VolunteerProfileController.update' },
  { method: 'PATCH', path: '/profile', name: 'profile.patch', middleware: ['auth', 'volunteer'], handler: 'volunteer/VolunteerProfileController.update' },
  { method: 'DELETE', path: '/profile', name: 'profile.destroy', middleware: ['auth', 'volunteer'], handler: 'volunteer/VolunteerProfileController.destroy' },
  { method: 'GET', path: '/profile/activity', name: 'profile.activity', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerProfileController.activity' },

  { method: 'POST', path: '/schools/drafts', name: 'schools.drafts.create', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.create_draft' },
  { method: 'GET', path: '/schools/drafts', name: 'schools.drafts.index', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.list_drafts' },
  { method: 'GET', path: '/schools/drafts/:id', name: 'schools.drafts.show', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.show_draft' },
  { method: 'PUT', path: '/schools/drafts/:id', name: 'schools.drafts.update', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.update_draft' },
  { method: 'PATCH', path: '/schools/drafts/:id', name: 'schools.drafts.patch', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.update_draft' },
  { method: 'DELETE', path: '/schools/drafts/:id', name: 'schools.drafts.delete', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.delete_draft' },
  { method: 'POST', path: '/schools/drafts/:id/submit', name: 'schools.drafts.submit', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.submit_draft' },

  { method: 'POST', path: '/schools', name: 'schools.submit', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.submit' },
  { method: 'GET', path: '/schools', name: 'schools.index', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.index' },
  { method: 'GET', path: '/schools/:id', name: 'schools.show', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.show' },
  { method: 'PUT', path: '/schools/:id', name: 'schools.update', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.update' },
  { method: 'PATCH', path: '/schools/:id', name: 'schools.patch', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.update' },
  { method: 'DELETE', path: '/schools/:id', name: 'schools.destroy', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.destroy' },
  { method: 'POST', path: '/schools/:id/submit', name: 'schools.submitExisting', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolController.submit_existing' },

  { method: 'GET', path: '/schools/:schoolId/operators', name: 'schools.operators.index', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolOperatorController.index' },
  { method: 'POST', path: '/schools/:schoolId/operators', name: 'schools.operators.store', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolOperatorController.store' },
  { method: 'GET', path: '/schools/:schoolId/operators/:id', name: 'schools.operators.show', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolOperatorController.show' },
  { method: 'PUT', path: '/schools/:schoolId/operators/:id', name: 'schools.operators.update', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolOperatorController.update' },
  { method: 'PATCH', path: '/schools/:schoolId/operators/:id', name: 'schools.operators.patch', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolOperatorController.update' },
  { method: 'DELETE', path: '/schools/:schoolId/operators/:id', name: 'schools.operators.destroy', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolOperatorController.destroy' },

  { method: 'GET', path: '/schools/:schoolId/location', name: 'schools.location.show', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolLocationController.show' },
  { method: 'PUT', path: '/schools/:schoolId/location', name: 'schools.location.upsert', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolLocationController.upsert' },
  { method: 'PATCH', path: '/schools/:schoolId/location', name: 'schools.location.patch', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolLocationController.update' },
  { method: 'DELETE', path: '/schools/:schoolId/location', name: 'schools.location.destroy', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolLocationController.destroy' },

  { method: 'GET', path: '/schools/:schoolId/children-stats', name: 'schools.childrenStats.show', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolChildrenStatsController.show' },
  { method: 'PUT', path: '/schools/:schoolId/children-stats', name: 'schools.childrenStats.upsert', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolChildrenStatsController.upsert' },
  { method: 'PATCH', path: '/schools/:schoolId/children-stats', name: 'schools.childrenStats.patch', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolChildrenStatsController.update' },
  { method: 'DELETE', path: '/schools/:schoolId/children-stats', name: 'schools.childrenStats.destroy', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolChildrenStatsController.destroy' },

  { method: 'GET', path: '/schools/:schoolId/welfare', name: 'schools.welfare.show', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolWelfareController.show' },
  { method: 'PUT', path: '/schools/:schoolId/welfare', name: 'schools.welfare.upsert', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolWelfareController.upsert' },
  { method: 'PATCH', path: '/schools/:schoolId/welfare', name: 'schools.welfare.patch', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolWelfareController.update' },
  { method: 'DELETE', path: '/schools/:schoolId/welfare', name: 'schools.welfare.destroy', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolWelfareController.destroy' },

  { method: 'GET', path: '/schools/:schoolId/photos', name: 'schools.photos.index', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolPhotoController.index' },
  { method: 'POST', path: '/schools/:schoolId/photos', name: 'schools.photos.store', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolPhotoController.store' },
  { method: 'GET', path: '/schools/:schoolId/photos/:id', name: 'schools.photos.show', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolPhotoController.show' },
  { method: 'PUT', path: '/schools/:schoolId/photos/:id', name: 'schools.photos.update', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolPhotoController.update' },
  { method: 'PATCH', path: '/schools/:schoolId/photos/:id', name: 'schools.photos.patch', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolPhotoController.update' },
  { method: 'DELETE', path: '/schools/:schoolId/photos/:id', name: 'schools.photos.destroy', middleware: ['auth', 'volunteer', 'profileComplete'], handler: 'volunteer/VolunteerSchoolPhotoController.destroy' },
];
